export const types = {
    GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE',

    GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_FAILURE: 'GET_MOVIE_FAILURE',

    SENT_EMAIL_REQUEST: 'SENT_EMAIL_REQUEST',
    SENT_EMAIL_SUCCESS: 'SENT_EMAIL_SUCCESS',
    SENT_EMAIL_FAILURE: 'SENT_EMAIL_FAILURE',

    RESET_MOVIE: 'RESET_MOVIE',
    RESET_SENT: 'RESET_SENT',

    OPEN_FAVORITES_EXISTS: 'OPEN_FAVORITES_EXISTS',

    ADD_FAVORITES: 'ADD_FAVORITES',
}